
/**
 * PRODUCTS ACTION TYPES
 */
export const LOAD_SUCCESS_PRODUCTS = 'LOAD_SUCCESS_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

/**
 * ORDER ACTION TYPES
 */
export const LOAD_SUCCESS_ORDERS = 'LOAD_SUCCESS_ORDERS';
export const LOAD_SUCCESS_ORDER = 'LOAD_SUCCESS_ORDER';
export const ERROR_ORDERS = 'ERROR_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';