export const LOAD_SUCCESS_PRODUCTS = 'LOAD_SUCCESS_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';